package hackathon_2020;

import java.util.Vector;

public class GUI extends javax.swing.JFrame {

	/**
	 * Creates new form GUI
	 */

	data_processing data_set;
	graphing grahps;
	search search_window;
	boolean created_search;
	
	private Vector<condensed_covid_data> data_points;
	String county_list[];

	public GUI(data_processing i) {
		data_set = i;
		data_points = i.getCondensed_covid_data_points();
		grahps = new graphing("title", i);
		created_search = false;
		create_list_counties();
		initComponents();

		// preset each of the sections
		int index = county_1_sel.getSelectedIndex();
		death_count_1.setText(String.valueOf(data_points.get(index).death_count));
		case_count_num_1.setText(String.valueOf(data_points.get(index).case_count));
		hosp_count_1.setText(String.valueOf(data_points.get(index).hospital_count));
		
		health_1.setText(String.valueOf(data_points.get(index).info.health_score));
		pov_1.setText(String.valueOf(data_points.get(index).info.poverty_rate));
		pop_1.setText(String.valueOf(data_points.get(index).info.population));
		food_1.setText(String.valueOf(data_points.get(index).money_for_food));

		index = county_2_sel.getSelectedIndex();
		death_count_2.setText(String.valueOf(data_points.get(index).death_count));
		case_count_num_2.setText(String.valueOf(data_points.get(index).case_count));
		hosp_count_2.setText(String.valueOf(data_points.get(index).hospital_count));
		
		health_2.setText(String.valueOf(data_points.get(index).info.health_score));
		pov_2.setText(String.valueOf(data_points.get(index).info.poverty_rate));
		pop_2.setText(String.valueOf(data_points.get(index).info.population));
		food_2.setText(String.valueOf(data_points.get(index).money_for_food));
	}

	private void create_list_counties() {
		county_list = new String[data_points.size()];
		for (int i = 0; i < data_points.size(); i++) {
			county_list[i] = data_points.get(i).county;
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        county_1_sel = new javax.swing.JComboBox<>();
        county_1_lab = new javax.swing.JLabel();
        county_2_sel = new javax.swing.JComboBox<>();
        county_2_lab = new javax.swing.JLabel();
        covid_graph_1 = new javax.swing.JButton();
        age_chart_1 = new javax.swing.JButton();
        groups_chart_1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        case_count_num_1 = new javax.swing.JLabel();
        hosp_count_1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        death_count_1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        covid_graph_2 = new javax.swing.JButton();
        age_chart_2 = new javax.swing.JButton();
        groups_chart_2 = new javax.swing.JButton();
        death_count_2 = new javax.swing.JLabel();
        hosp_count_2 = new javax.swing.JLabel();
        case_count_num_2 = new javax.swing.JLabel();
        adv_search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        health_1 = new javax.swing.JLabel();
        pov_1 = new javax.swing.JLabel();
        pop_1 = new javax.swing.JLabel();
        food_1 = new javax.swing.JLabel();
        food_2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pop_2 = new javax.swing.JLabel();
        pov_2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        health_2 = new javax.swing.JLabel();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		county_1_sel.setModel(new javax.swing.DefaultComboBoxModel<>(county_list));
		county_1_sel.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				county_1_selItemStateChanged(evt);
			}
		});

		county_1_lab.setText("county 1");

		county_2_sel.setModel(new javax.swing.DefaultComboBoxModel<>(county_list));
		county_2_sel.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				county_2_selItemStateChanged(evt);
			}
		});

		county_2_lab.setText("County 2");

		covid_graph_1.setText("covid graph");
		covid_graph_1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				covid_graph_1MouseClicked(evt);
			}
		});

		age_chart_1.setText("age groups affected");
		age_chart_1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				age_chart_1MouseClicked(evt);
			}
		});
		age_chart_1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				age_chart_1ActionPerformed(evt);
			}
		});

		groups_chart_1.setText("groups affected");
		groups_chart_1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				groups_chart_1MouseClicked(evt);
			}
		});
		groups_chart_1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				groups_chart_1ActionPerformed(evt);
			}
		});

		jLabel1.setText("case count");

		case_count_num_1.setText("0");

		hosp_count_1.setText("0");

		jLabel6.setText("Hospitalized Count");

		jLabel7.setText("death count");

		death_count_1.setText("0");

		jLabel9.setText("case count");

		jLabel10.setText("Hospitalized Count");

		jLabel11.setText("death count");

		covid_graph_2.setText("covid graph");
		covid_graph_2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				covid_graph_2MouseClicked(evt);
			}
		});

		age_chart_2.setText("age groups affected");
		age_chart_2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				age_chart_2MouseClicked(evt);
			}
		});
		age_chart_2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				age_chart_2ActionPerformed(evt);
			}
		});

		groups_chart_2.setText("groups affected");
		groups_chart_2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				groups_chart_2MouseClicked(evt);
			}
		});
		groups_chart_2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				groups_chart_2ActionPerformed(evt);
			}
		});

		death_count_2.setText("0");

		hosp_count_2.setText("0");

		case_count_num_2.setText("0");

		adv_search.setText("advanced search");
        adv_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adv_searchMouseClicked(evt);
            }
        });
		
        jLabel3.setText("health score");

        jLabel4.setText("poverty percent");

        jLabel5.setText("population");

        jLabel8.setText("amount for food");

        health_1.setText("0");

        pov_1.setText("0");

        pop_1.setText("0");

        food_1.setText("0");

        food_2.setText("0");

        jLabel12.setText("amount for food");

        jLabel13.setText("population");

        pop_2.setText("0");

        pov_2.setText("0");

        jLabel14.setText("poverty percent");

        jLabel15.setText("health score");

        health_2.setText("0");
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(county_1_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(county_1_sel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(county_2_sel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(county_2_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(age_chart_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(covid_graph_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(groups_chart_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(age_chart_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(covid_graph_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(groups_chart_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(death_count_1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(case_count_num_1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hosp_count_1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(food_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pop_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pov_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(health_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(29, 29, 29)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(death_count_2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(case_count_num_2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hosp_count_2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(adv_search))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(health_2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                            .addComponent(pov_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pop_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(food_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(county_1_lab)
                    .addComponent(county_2_lab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(county_2_sel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(county_1_sel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(case_count_num_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hosp_count_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(death_count_1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(case_count_num_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hosp_count_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(death_count_2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(health_1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pov_1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pop_1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(food_1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(health_2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(pov_2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(pop_2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(food_2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(covid_graph_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(age_chart_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(groups_chart_1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(covid_graph_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(age_chart_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(groups_chart_2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adv_search)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
	}// </editor-fold>

	private void age_chart_1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void groups_chart_1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void age_chart_2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void groups_chart_2ActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void covid_graph_2MouseClicked(java.awt.event.MouseEvent evt) {
		int index = county_2_sel.getSelectedIndex();
		//System.out.println("creating covid graph for county2: " + index);
		grahps.create_covid_graph(index, 2);
	}

	private void age_chart_2MouseClicked(java.awt.event.MouseEvent evt) {
		int index = county_2_sel.getSelectedIndex();
		//System.out.println("creating group cart for county2: " + index);
		grahps.create_pie_chart(index, 2, true);
	}

	private void groups_chart_2MouseClicked(java.awt.event.MouseEvent evt) {
		int index = county_2_sel.getSelectedIndex();
		//System.out.println("creating age cart for county2: " + index);
		grahps.create_pie_chart(index, 2, false);
	}

	private void covid_graph_1MouseClicked(java.awt.event.MouseEvent evt) {
		int index = county_1_sel.getSelectedIndex();
		//System.out.println("creating covid graph for county1: " + index);
		grahps.create_covid_graph(index, 1);
	}

	private void age_chart_1MouseClicked(java.awt.event.MouseEvent evt) {
		int index = county_1_sel.getSelectedIndex();
		//System.out.println("creating age cart for county1: " + index);
		grahps.create_pie_chart(index, 1, true);
	}

	private void groups_chart_1MouseClicked(java.awt.event.MouseEvent evt) {
		int index = county_1_sel.getSelectedIndex();
		//System.out.println("creating groups cart for county1: " + index);
		grahps.create_pie_chart(index, 1, false);
	}

	private void county_2_selItemStateChanged(java.awt.event.ItemEvent evt) {
		//System.out.println(county_2_sel.getSelectedIndex());// what index posiition in the list is changed to
		int index = county_2_sel.getSelectedIndex();
		death_count_2.setText(String.valueOf(data_points.get(index).death_count));
		case_count_num_2.setText(String.valueOf(data_points.get(index).case_count));
		hosp_count_2.setText(String.valueOf(data_points.get(index).hospital_count));
		
		health_2.setText(String.valueOf(data_points.get(index).info.health_score));
		pov_2.setText(String.valueOf(data_points.get(index).info.poverty_rate));
		pop_2.setText(String.valueOf(data_points.get(index).info.population));
		food_2.setText(String.valueOf(data_points.get(index).money_for_food));
	}

	private void county_1_selItemStateChanged(java.awt.event.ItemEvent evt) {
		//System.out.println(county_1_sel.getSelectedIndex());// what index posiition in the list is changed to
		int index = county_1_sel.getSelectedIndex();
		death_count_1.setText(String.valueOf(data_points.get(index).death_count));
		case_count_num_1.setText(String.valueOf(data_points.get(index).case_count));
		hosp_count_1.setText(String.valueOf(data_points.get(index).hospital_count));
		
		health_1.setText(String.valueOf(data_points.get(index).info.health_score));
		pov_1.setText(String.valueOf(data_points.get(index).info.poverty_rate));
		pop_1.setText(String.valueOf(data_points.get(index).info.population));
		food_1.setText(String.valueOf(data_points.get(index).money_for_food));
	}

    private void adv_searchMouseClicked(java.awt.event.MouseEvent evt) {                                        
    	 java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new search(data_set).setVisible(true);
	            }
	        });
    } 
	
	// Variables declaration - do not modify
    private javax.swing.JButton adv_search;
    private javax.swing.JButton age_chart_1;
    private javax.swing.JButton age_chart_2;
    private javax.swing.JLabel case_count_num_1;
    private javax.swing.JLabel case_count_num_2;
    private javax.swing.JLabel county_1_lab;
    private javax.swing.JComboBox<String> county_1_sel;
    private javax.swing.JLabel county_2_lab;
    private javax.swing.JComboBox<String> county_2_sel;
    private javax.swing.JButton covid_graph_1;
    private javax.swing.JButton covid_graph_2;
    private javax.swing.JLabel death_count_1;
    private javax.swing.JLabel death_count_2;
    private javax.swing.JLabel food_1;
    private javax.swing.JLabel food_2;
    private javax.swing.JButton groups_chart_1;
    private javax.swing.JButton groups_chart_2;
    private javax.swing.JLabel health_1;
    private javax.swing.JLabel health_2;
    private javax.swing.JLabel hosp_count_1;
    private javax.swing.JLabel hosp_count_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pop_1;
    private javax.swing.JLabel pop_2;
    private javax.swing.JLabel pov_1;
    private javax.swing.JLabel pov_2;
	// End of variables declaration
}
